[package]
name = "ciphercanvas-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.1", features = ["derive"] }
qrcode = "0.12"
structopt = "0.3"
toml = "0.8"
